<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Backend\Block\Widget\Form\Container */
 ?>
<?php if ($block->getButtonsHtml('header')): ?>
    <div class="page-form-actions" <?php /* @escapeNotVerified */ echo $block->getUiId('content-header') ?>><?php echo $block->getButtonsHtml('header') ?></div>
<?php endif; ?>
<?php echo $block->getFormHtml() ?>
<?php if ($block->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $block->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>

<script>
require(["MXWidgetComponentSubWidget"], function() {
    <?php echo $this->getFormHandlerJsObj(); ?> = new SubWidget.FormHandler("<?php echo $this->getTargetElementId(); ?>");
});
</script>
